# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puretacodiet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('meal', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='puretacodiet.Meal')),
            ],
        ),
        migrations.CreateModel(
            name='PlanInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('plan', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='puretacodiet.Plan')),
            ],
        ),
    ]
