# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puretacodiet', '0003_auto_20170825_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField(help_text='Quantity of this product.')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Number of Tacos.', max_digits=3)),
                ('uom', models.CharField(choices=[('OZ', 'Ounce'), ('EA', 'Each')], default='OZ', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of the Vendor.')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='puretacodiet.Vendor'),
        ),
    ]
