# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puretacodiet', '0004_auto_20171014_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanInstanceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planinstance', models.ManyToManyField(to='puretacodiet.PlanInstance')),
            ],
        ),
    ]
