# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puretacodiet', '0006_auto_20171015_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(help_text='enter your username')),
                ('password', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puretacodiet.Vendor')),
            ],
        ),
    ]
