# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puretacodiet', '0007_externalcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(max_length=250)),
                ('city', models.CharField(choices=[('Louisville', 'Louisville')], default='Louisville', max_length=25)),
                ('state', models.CharField(choices=[('KY', 'Kentucky')], default='KY', max_length=2)),
                ('zip', models.IntegerField()),
                ('homephone', models.CharField(max_length=10)),
                ('mobilephome', models.CharField(max_length=10)),
            ],
        ),
    ]
