# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puretacodiet', '0010_auto_20171015_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(choices=[('OZ', 'Ounce'), ('EA', 'Each')], default='OZ', max_length=2)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('OZ', 'Ounce'), ('EA', 'Each')], default='OZ', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='offerprice',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Offer Price.', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='offerquantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='orderby',
            field=models.CharField(choices=[('UNIT', 'UNIT'), ('WEIGHT', 'WEIGHT')], default='UNIT', max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='regularprice',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Regular Price.', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='saleprice',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Sale Price.', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='soldby',
            field=models.CharField(choices=[('UNIT', 'UNIT'), ('WEIGHT', 'WEIGHT')], default='UNIT', max_length=8),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='product',
            field=models.ForeignKey(blank='False', null='False', on_delete=django.db.models.deletion.CASCADE, to='puretacodiet.Product'),
        ),
    ]
